Library_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from library import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',include('library.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from library import views

urlpatterns = [
    path('home/', views.index, name='home'),
    path('register',views.register,name='register'),
    path('std_login/',views.std_login,name='std_login'),
    path('user_login/',views.user_login_success, name='user_login'),
    path('logout',views.std_logout,name='logout'),
    path('search_b/',views.search_book,name='search_b'),
    path('issue_book/',views.issue_book,name='issue_book'),
    path('delete_issue/',views.delete_issue,name='delete_issue'),
    path('renewal/',views.renewal, name = 'renewal'),
    path('get_all_user/',views.get_all_user, name='get_all_user'),
    path('checkout/',views.checkout,name='checkout'),
    path('book_detail/',views.book_detail,name='book_detail'),
    path('return_book',views.return_book, name='return_book'),
    path('superuser_login', views.superuser_login, name='superuser_login'),
    path('admin_login',views.admin_login_success, name='admin_login'),
    path('admin_logout',views.admin_logout, name ='admin_logout')
]

library/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Book(models.Model):
    isbn = models.CharField('ISBN', max_length=13,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class StudentProfile(models.Model):
    user = models.OneToOneField(User ,on_delete=models.CASCADE)

    book1 = models.CharField(blank=True,max_length=10)
    book2 = models.CharField(blank=True,max_length=10)
    book3 = models.CharField(blank=True,max_length=10)
    book4 = models.CharField(blank=True,max_length=10)

    def __str__(self):
        return self.user.username

class Add_No(models.Model):
    AVAILABILITY = (
        ('I','Issued'),
        ('A','Available'),
    )
    book_name = models.ForeignKey(Book,on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(StudentProfile,null=True,blank=True,on_delete=models.SET_NULL)
    book_no = models.CharField(max_length=10)
    shelf_no = models.CharField(max_length=5)
    availability = models.CharField(max_length=2,choices=AVAILABILITY,default='A')
    issued_on = models.DateField(auto_now=True)
    reissue_cycle = models.IntegerField(default=1)

    def __str__(self):
        return self.book_no

class Semester_Book(models.Model):
    SEMESTER = (
        ('Semester-1','Semester-1'),
        ('Semester-2','Semester-2'),
        ('Semester-3','Semester-3'),
        ('Semester-4','Semester-4'),
        ('Semester-5','Semester-5'),
        ('Semester-6','Semester-6'),
        ('Semester-7','Semester-7'),
        ('Semester-8','Semester-8'),
    )
    semester = models.CharField(max_length=10,choices=SEMESTER,default=None)
    book1_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book2_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book3_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book4_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book5_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book6_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book7_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book8_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book9_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book10_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book11_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    book12_isbn = models.CharField(max_length=13,default=None,blank=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    def __str__(self):
        return self.semester

templates/adminpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <link rel="stylesheet" href="{% static "css/loggeduser.css" %}">
    <title>IIITL Library</title>
</head>
<body>
    <div class="main_header"><img src="{% static "images/logo.png" %}" alt="Logo IIIT Lucknow" class="main_logo"/><div class="main_title">Central Library, Indian Institute of Information Technology, Lucknow<br>केंद्रीय पुस्तकालय, भारतीय सूचना प्रौद्योगिकी संस्थान, लखनऊ</div></div>
    <!-- <div class="main_title_lib">CENTRAL LIBRARY<br>केंद्रीय पुस्तकालय</div> -->
    <div class="navigation" style="background-color: #e3f2fd;">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin_logout' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Resources</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Services
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item right">
                <a class="nav-link" href="#">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://iiitl.ac.in/">IIITL Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_logout' %}">Logout({{user.username}})</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="user_welcome">Welcome Admin ({{user.username}})</div>
    <div class="container" style="width: 50%;">
        <form class="return_form" action="{% url 'return_book' %}" method="POST" style="border: 1px solid #bdc3c7;">
        {% csrf_token %}
        <div class="form-group" style="padding: 20px 20px 0 20px;">
            <label for="book_no">Book Number</label>
            <input type="text" name="book_no" class="form-control" id="book_no" placeholder="Enter Book Number">
            {% if message_failure %}
            <small class="form-text" style="color: red;">{{message_failure}}</small>
            {% endif %}
            {% if message_success %}
            <small class="form-text" style="color: green;">{{message_success}}</small>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary" style="margin: 20px">Return Book</button>
        </form>
        <div style="margin-top: 20px;"> <a href="{% url 'get_all_user' %}">Get current fine of all user.</a> </div>
        {% if fine %}
        <table>
          <tr>
            <th>User</th>
            <th>Book Number</th>
            <th>Fine(Rs.)</th>
            <th>Total Fine(Rs.)</th>
          </th>
          {% for f in fine %}
          <tr>
            <td rowspan={{ f.3 }}>{{ f.0 }}</td>
            <td>{{ f.1.0.0 }}</td>
            <td>{{ f.1.0.1 }}</td>
            <td rowspan={{ f.3 }}>{{ f.2 }}</td>
          </tr>
          {% if f.1.1 %}
            <tr>
              <td>{{ f.1.1.0 }}</td>
              <td>{{ f.1.1.1 }}</td>
            </tr>
          {% endif %}
          {% if f.1.2 %}
            <tr>
              <td>{{ f.1.2.0 }}</td>
              <td>{{ f.1.2.1 }}</td>
            </tr>
          {% endif %}
          {% if f.1.3 %}
            <tr>
              <td>{{ f.1.3.0 }}</td>
              <td>{{ f.1.3.1 }}</td>
            </tr>
          {% endif %}
          {% endfor %}
        </table>
        {% endif %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/book_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>IIITL Library</title>
  </head>
  <body>
    <div class="main_header"><img src="{% static "images/logo.png" %}" alt="Logo IIIT Lucknow" class="main_logo"/><div class="main_title">Central Library, Indian Institute of Information Technology, Lucknow<br>केंद्रीय पुस्तकालय, भारतीय सूचना प्रौद्योगिकी संस्थान, लखनऊ</div></div>
    <!-- <div class="main_title_lib">CENTRAL LIBRARY<br>केंद्रीय पुस्तकालय</div> -->
    <div class="navigation" style="background-color: #e3f2fd;">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_login' %}">Student Home({{user.first_name}})</a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Resources</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Services
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item right">
                <a class="nav-link" href="#">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://iiitl.ac.in/">IIITL Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout({{user.first_name}})</a>
            </li>
          {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% if b_details %}
      <div class="container" style="margin-top: 3rem;">
          <div style="display: flex; flex-direction: column; justify-content: center;">
              <div style="font-size: 1.8rem ;margin-bottom: 1rem;">{{b_details.1}}</div>
              <div style="display: flex; flex-direction: row; justify-content: space-evenly; align-items: center;">
                  <div>
                      <img src={{b_details.0}} alt={{b_details.1}} width="200px" height="auto">
                  </div>
                  <div style="display: flex; flex-direction: column; margin-left: 3rem;">
                      <div style="font-weight: bold;">Author/s : 
                        {% for author in b_details.2 %}
                          <span style="font-weight: lighter;">{{author}} </span>
                        {% endfor %}
                      </div>
                      <div style="font-weight: bold;">ISBN : <span style="font-weight: lighter;">{{b_details.3.0}} / {{b_details.3.1}}</span></div>
                      <div style="font-weight: bold;">Categories :
                        {% for category in b_details.4 %}
                          <span style="font-weight: lighter;">{{category}}</span>
                        {% endfor %}
                      </div>
                      <div style="font-weight: bold;">Language : <span style="font-weight: lighter;">{{b_details.5}}</span></div>
                      <div style="font-size: 14px;">{{b_details.6}}</div>
                  </div>
              </div>
          </div>
      </div>
      {% else %}
      <div class="container"> 
        No Information Found.
      </div>
    {% endif %}  



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/book_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <link rel="stylesheet" href="{% static "css/book_list.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>IIITL Library</title>
  </head>
  <body>
    <div class="main_header"><img src="{% static "images/logo.png" %}" alt="Logo IIIT Lucknow" class="main_logo"/><div class="main_title">Central Library, Indian Institute of Information Technology, Lucknow<br>केंद्रीय पुस्तकालय, भारतीय सूचना प्रौद्योगिकी संस्थान, लखनऊ</div></div>
    <!-- <div class="main_title_lib">CENTRAL LIBRARY<br>केंद्रीय पुस्तकालय</div> -->
    <div class="navigation" style="background-color: #e3f2fd;">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_login' %}">Student Home({{user.first_name}})</a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Resources</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Services
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item right">
                <a class="nav-link" href="#">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://iiitl.ac.in/">IIITL Home</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout({{user.first_name}})</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
        <div class="search_box">
          <form class="my-2 my-lg-0" action="{% url 'search_b' %}" method="GET">
              <div style="display: flex;">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="search-by" id="inlineRadio1" value="title" checked>
                <label class="form-check-label" for="inlineRadio1">Title</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="search-by" id="inlineRadio2" value="author">
                <label class="form-check-label" for="inlineRadio2">Author</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="search-by" id="inlineRadio3" value="isbn">
                <label class="form-check-label" for="inlineRadio3">ISBN</label>
              </div>
            </form>
        </div>
    <div class="jumbotron">
        <div class="book_list_header">Book List</div>

        <!-- {% if book_info %}
        {% for b in book_info %}
        <div>{{b.book_no}}</div>
        {% endfor %}
        {% endif%} -->
    
        {% if book_list %}
        <table>
            <tr>
                <th>Book Number</th>
                <th>ISBN</th>
                <th>Title</th>
                <th>Author</th>
                <th>Shelf Number</th>
                <th>Availability</th>
            </tr>
            {% for book in book_list %}
              <form action="{% url 'book_detail' %}" method="GET">
                <tr>
                  <td>{{ book.1.book_no }}</td>
                  <td><input type="hidden" name='isbn_no' value={{ book.0.isbn }}>{{ book.0.isbn }}</td>
                  <td><button style="border: hidden; color: blue;" type="submit">{{ book.0.title }}</button></td>
                  <td>{{ book.0.author }}</td>
                  <td>{{ book.1.shelf_no }}</td>
                  <td>{{ book.1.get_availability_display }}</td>
                </tr>
              </form>
            
            {% endfor %}
        </table>
        {% else %}
        <div>There are no books related to given search.</div>
        {% endif %}
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/test.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>IIITL Library</title>
  </head>
  <body>
    <div class="loader-wrapper">
      <span class="loader"><span class="loader-inner"></span></span>
    </div>
    <div class="content">
      <img src="https://picsum.photos/300/300/?random" />
 </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>